include: package:lints/recommended.yaml

analyzer:
  exclude:
    - '**/*.g.dart'
    - 'build/**'

formatter:
  page_width: 80
  trailing_commas: preserve

# Lint rules and documentation, see https://dart.dev/tools/linter-rules
linter:
  rules:
    - cancel_subscriptions
    - close_sinks
    - hash_and_equals
    - test_types_in_equals
    - unrelated_type_equality_checks
    - valid_regexps
    - prefer_final_fields
    - prefer_final_in_for_each
    - prefer_final_locals
    - lines_longer_than_80_chars
    - require_trailing_commas
    - prefer_single_quotes
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
