// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// **************************************************************************

// Generated by owl 0.2.2
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'token_request.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

/// Mapper for TokenRequest
abstract class TokenRequestMapper {
  /// Converts an instance of TokenRequest to Map.
  static Map<String, dynamic> map(TokenRequest object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('grant_type', object.grantType))
        .toMap();
  }

  /// Converts a Map to an instance of TokenRequest.
  static TokenRequest parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final TokenRequest object = new TokenRequest();
    object.grantType = map['grant_type'];
    return object;
  }

  /// Converts a JSON string to an instance of TokenRequest.
  static TokenRequest fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of TokenRequest to JSON string.
  static String toJson(TokenRequest object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

/// Mapper for ApiToken
abstract class ApiTokenMapper {
  /// Converts an instance of ApiToken to Map.
  static Map<String, dynamic> map(ApiToken object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('access_token', object.accessToken)
          ..put('token_type', object.tokenType)
          ..put('expires_in', object.expiresIn))
        .toMap();
  }

  /// Converts a Map to an instance of ApiToken.
  static ApiToken parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final ApiToken object = new ApiToken();
    object.accessToken = map['access_token'];
    object.tokenType = map['token_type'];
    object.expiresIn = map['expires_in'];
    return object;
  }

  /// Converts a JSON string to an instance of ApiToken.
  static ApiToken fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of ApiToken to JSON string.
  static String toJson(ApiToken object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
