// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Generator: JsonGenerator
// Target: library spotify
// **************************************************************************

// Generated by owl 0.2.1
// https://github.com/agilord/owl

// ignore: unused_import, library_prefixes
import 'spotify_browser.dart';
// ignore: unused_import, library_prefixes
import 'dart:convert';
// ignore: unused_import, library_prefixes
import 'package:owl/util/json/core.dart' as _owl_json;

// **************************************************************************
// Generator: JsonGenerator
// Target: class TokenRequest
// **************************************************************************

/// Mapper for TokenRequest
abstract class TokenRequestMapper {
  /// Converts an instance of TokenRequest to Map.
  static Map<String, dynamic> map(TokenRequest object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('grant_type', object.grantType))
        .toMap();
  }

  /// Converts a Map to an instance of TokenRequest.
  static TokenRequest parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final TokenRequest object = new TokenRequest();
    object.grantType = map['grant_type'];
    return object;
  }

  /// Converts a JSON string to an instance of TokenRequest.
  static TokenRequest fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of TokenRequest to JSON string.
  static String toJson(TokenRequest object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class ApiToken
// **************************************************************************

/// Mapper for ApiToken
abstract class ApiTokenMapper {
  /// Converts an instance of ApiToken to Map.
  static Map<String, dynamic> map(ApiToken object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('access_token', object.accessToken)
          ..put('token_type', object.tokenType)
          ..put('expires_in', object.expiresIn))
        .toMap();
  }

  /// Converts a Map to an instance of ApiToken.
  static ApiToken parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final ApiToken object = new ApiToken();
    object.accessToken = map['access_token'];
    object.tokenType = map['token_type'];
    object.expiresIn = map['expires_in'];
    return object;
  }

  /// Converts a JSON string to an instance of ApiToken.
  static ApiToken fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of ApiToken to JSON string.
  static String toJson(ApiToken object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Artist
// **************************************************************************

/// Mapper for Artist
abstract class ArtistMapper {
  /// Converts an instance of Artist to Map.
  static Map<String, dynamic> map(Artist object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('href', object.href)
          ..put('id', object.id)
          ..put('name', object.name)
          ..put('type', object.type)
          ..put('uri', object.uri)
          ..put('followers', FollowersMapper.map(object.followers))
          ..put('genres', object.genres?.toList())
          ..put('images', object.images?.map(ImageMapper.map)?.toList())
          ..put('popularity', object.popularity))
        .toMap();
  }

  /// Converts a Map to an instance of Artist.
  static Artist parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Artist object = new Artist();
    object.href = map['href'];
    object.id = map['id'];
    object.name = map['name'];
    object.type = map['type'];
    object.uri = map['uri'];
    object.followers = FollowersMapper.parse(map['followers']);

    // ignore: avoid_as
    object.genres = (map['genres'] as List<String>)?.toList();

    // ignore: avoid_as
    object.images =
        (map['images'] as List<dynamic>)?.map(ImageMapper.parse)?.toList();
    object.popularity = map['popularity'];
    return object;
  }

  /// Converts a JSON string to an instance of Artist.
  static Artist fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Artist to JSON string.
  static String toJson(Artist object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class ArtistSimple
// **************************************************************************

/// Mapper for ArtistSimple
abstract class ArtistSimpleMapper {
  /// Converts an instance of ArtistSimple to Map.
  static Map<String, dynamic> map(ArtistSimple object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('href', object.href)
          ..put('id', object.id)
          ..put('name', object.name)
          ..put('type', object.type)
          ..put('uri', object.uri))
        .toMap();
  }

  /// Converts a Map to an instance of ArtistSimple.
  static ArtistSimple parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final ArtistSimple object = new ArtistSimple();
    object.href = map['href'];
    object.id = map['id'];
    object.name = map['name'];
    object.type = map['type'];
    object.uri = map['uri'];
    return object;
  }

  /// Converts a JSON string to an instance of ArtistSimple.
  static ArtistSimple fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of ArtistSimple to JSON string.
  static String toJson(ArtistSimple object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Followers
// **************************************************************************

/// Mapper for Followers
abstract class FollowersMapper {
  /// Converts an instance of Followers to Map.
  static Map<String, dynamic> map(Followers object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('href', object.href)
          ..put('total', object.total))
        .toMap();
  }

  /// Converts a Map to an instance of Followers.
  static Followers parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Followers object = new Followers();
    object.href = map['href'];
    object.total = map['total'];
    return object;
  }

  /// Converts a JSON string to an instance of Followers.
  static Followers fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Followers to JSON string.
  static String toJson(Followers object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}

// **************************************************************************
// Generator: JsonGenerator
// Target: class Image
// **************************************************************************

/// Mapper for Image
abstract class ImageMapper {
  /// Converts an instance of Image to Map.
  static Map<String, dynamic> map(Image object) {
    if (object == null) return null;
    return (new _owl_json.MapBuilder(ordered: false)
          ..put('height', object.height)
          ..put('width', object.width)
          ..put('url', object.url))
        .toMap();
  }

  /// Converts a Map to an instance of Image.
  static Image parse(Map<String, dynamic> map) {
    if (map == null) return null;
    final Image object = new Image();
    object.height = map['height'];
    object.width = map['width'];
    object.url = map['url'];
    return object;
  }

  /// Converts a JSON string to an instance of Image.
  static Image fromJson(String json) {
    if (json == null || json.isEmpty) return null;
    final Map<String, dynamic> map = JSON.decoder.convert(json);
    return parse(map);
  }

  /// Converts an instance of Image to JSON string.
  static String toJson(Image object) {
    if (object == null) return null;
    return JSON.encoder.convert(map(object));
  }
}
